services:
  - type: web
    name: guardcore-api
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ASPNETCORE_URLS
        value: http://+:5000
      - key: Jwt__Key
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: guardcore-db
          property: connectionString

databases:
  - name: guardcore-db
    plan: free
    databaseName: guardcore
    user: guardcore
