name: security_guard_app
description: A cross-platform app for Super Admin and user management, QR code generation, and reporting.
version: 1.0.0+1
environment:
  sdk: ">=3.0.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  qr_flutter: ^4.1.0
  qr_code_scanner: ^1.0.1
  flutter_email_sender: ^8.0.0
  provider: ^6.1.2
  url_launcher: ^6.1.10
  http: ^1.1.0
  uuid: ^4.0.0
  window_manager: ^0.3.7
  printing: ^5.12.0
  pdf: ^3.10.8
  intl: ^0.19.0
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
